### ISSUE TITLE
Please don't change font settings

### ISSUE THREAD

**Issue by lmartins** [GlennEngelen/liquid-ui#1]
While this seems like a really cool theme, it does something I don't think it's ideal.
When activating both the theme a syntax for liquid-ui, it changes my font-settings, making them way smaller than I was using.

If possible, it would be really nice to keep the elasticity of the One Dark theme, making things bigger as the window grows.

Cheers.

**Comment by GlennEngelen** [comment]
Thanks for the heads up!
Will be fixed in the next commit.

**Comment by GlennEngelen** [comment]
Should be fixed!
